config/routes.rb
Rails.application.routes.draw do
  get 'terms' => 'terms_of_service#index'

  get 'about' => 'about#index'


  root 'home#index'

  resources :advertisements








end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  validates :dish, presence: true
  validates :phone, presence: true
  validates_format_of :phone, with: /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}\z/, message: "Invalid phone number. Please enter a phone number in the format 000-000-0000"
  validates :price, presence: true, numericality: { message: "Invalid price. Please enter a valid decimal number" }
  validates :location, presence: true
  validates :description, presence: true

  scope :latest, ->(amount) { order(created_at: :desc).first(amount) }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/about_controller_controller.rb
class AboutControllerController < ApplicationController
  def index
  end
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.paginate(page: params[:page], per_page: 20)
  end

  def show
  end

  def new
    @advertisement = Advertisement.new
  end

  def create
    @advertisement = Advertisement.new(advert_params)

    if @advertisement.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def advert_params
    params.require(:advertisement).permit(:dish, :phone, :price, :location, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @advertisements = Advertisement.latest(10)
  end
end

app/controllers/terms_of_service_controller.rb
class TermsOfServiceController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="window">
  <h1>Coming Soon!</h1>
</div>

app/views/advertisements/_form.html.erb
<%= form_for advertisement do |f| %>
  <%= f.label :dish %>
  <% advertisement.errors[:dish].each do |msg| %>
    <div class="form_error"><%= msg %></div>
  <% end %>
  <%= f.text_field :dish, placeholder: "The name of your dish" %>

  <%= f.label :price %>
  <% advertisement.errors[:price].each do |msg| %>
    <div class="form_error"><%= msg %></div>
  <% end %>
  <%= f.text_field :price, placeholder: "0.00" %>

  <%= f.label :phone %>
  <% advertisement.errors[:phone].each do |msg| %>
    <div class="form_error"><%= msg %></div>
  <% end %>
  <%= f.text_field :phone, placeholder: "A valid phone number" %>

  <%= f.label :location %>
  <% advertisement.errors[:location].each do |msg| %>
    <div class="form_error"><%= msg %></div>
  <% end %>
  <%= f.text_field :location, placeholder: "Your locale or nearest cross street" %>

  <%= f.label :description %>
  <% advertisement.errors[:description].each do |msg| %>
    <div class="form_error"><%= msg %></div>
  <% end %>
  <%= f.text_area :description, rows: 5, placeholder: "A short description. Don't forget to include a time it will be ready by!" %>

  <%= f.submit %>
<% end %>

app/views/advertisements/index.html.erb
<div class="window">
  <h1 class="page-title">Browse Various Dishes</h1>

  <h2 class="subtitle">Most Recent Dishes</h2>
  <%= will_paginate @advertisements %>
  <%= render 'shared/advertisements', advertisements: @advertisements %>
  <%= will_paginate @advertisements %>
</div>

app/views/advertisements/new.html.erb
<div class="window">
  <h1>Submit a Dish!</h1>
  <%= render 'form', advertisement: @advertisement %>
</div>

app/views/home/index.html.erb
<div class="window">
  <%= image_tag 'logo.png' %>
  <h1 id="home-intro">Welcome to Appetite!</h1>

  <h2 class="subtitle">Latest Dishes Yo</h2>
  <%= render 'shared/advertisements', advertisements: @advertisements %>
</div>

app/views/shared/_advertisements.html.erb
<table class="ads-table">
  <thead>
    <tr>
      <th>Dish</th>
      <th>Contact</th>
      <th>Price</th>
      <th>Location</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  <% advertisements.each do |ad| %>
    <tr>
      <td><%= ad.dish %></td>
      <td><%= ad.phone %></td>
      <td>$<%= ad.price %></td>
      <td><%= ad.location %></td>
      <td><%= ad.description %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/shared/_topbar.html.erb
<nav class="topbar">
  <div class="mobile-menu-button">
    <div class="bar" id="bar1"></div>
    <div class="bar" id="bar2"></div>
    <div class="bar" id="bar3"></div>
  </div>
  <div class="mobile-logo">
    <%= image_tag 'logo.png' %>
  </div>
  <ul class="clear">
    <li id="logo-list-item">
      <%= link_to root_path, id: 'top-bar-logo' do %>
        <%= image_tag 'menu_icon.png' %>
      <% end %>
    </li>
    <li><%= link_to 'Browse', advertisements_path %></li>
    <li><%= link_to 'Submit a Dish!', new_advertisement_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Terms of Use', terms_path %></li>
  </ul>
</nav>